type NoServiceType = { [region: string]: string[] | undefined };
export const noservice : NoServiceType = {
    'af-south-1': ['serverlessrepo'],
    'me-south-1' : [''],
    'me-north-1' : [''],
    'sa-east-1' : [''],
    'us-gov-east-1' : [''],
    'us-gov-west-1' : [''],
    'cn-north-1' : [''],
    'cn-northwest-1' : [''],
    'ap-east-1' : [''],
    'ap-northeast-1' : [''],
    'ap-northeast-2' : [''],
    'ap-northeast-3' : ['serverlessrepo'],
    'ap-south-1' : [''],
    'ap-south-2' : ['serverlessrepo'],
    'ap-southeast-1' : [''],
    'ap-southeast-2' : [''],
    'ap-southeast-3' : ['serverlessrepo'],
    'ap-southeast-4' : ['serverlessrepo'],
    'ca-central-1' : [''],
    'ca-central-2' : [''],
    'eu-central-1' : [''],
    'eu-central-2': ['serverlessrepo','redshift-serverless'],
    'eu-north-1' : [''],
    'eu-north-2' : [''],
    'eu-west-1' : [''],
    'eu-west-2' : [''],
    'eu-west-3' : [''],
    'eu-west-4' : [''],
    'eu-south-1' : ['serverlessrepo'],
    'eu-south-2' : ['serverlessrepo'],
    'us-east-1' : [''],
    'us-east-2' : [''],
    'us-west-1' : [''],
    'us-west-2' : [''],
    'il-central-1' : ['serverlessrepo']
};