
export const regionCategoryMapping = new Map([
    ['eu-west-1', 'Europe'], 
    ['eu-west-2', 'Europe'], 
    ['eu-west-3', 'Europe'], 
    ['eu-north-1', 'Europe'], 
    ['eu-north-2', 'Europe'], 
    ['eu-central-1', 'Europe'],
    ['eu-central-2', 'Europe'],  
    ['eu-south-1', 'Europe'],
    ['eu-south-2', 'Europe'], 
    ['eu-west-4', 'Europe'],
    ['af-south-1', 'Africa'], 
    ['us-east-1', 'US East'], 
    ['us-east-2', 'US East'], 
    ['us-gov-east-1', 'US East'], 
    ['us-west-1', 'US West'], 
    ['us-west-2', 'US West'], 
    ['us-gov-west-1', 'US West'], 
    ['sa-east-1', 'South America'], 
    ['ca-central-1', 'Canada'], 
    ['ca-central-2', 'Canada'], 
    ['ap-south-1', 'Asia Pacific'], 
    ['ap-northeast-1', 'Asia Pacific'], 
    ['ap-northeast-2', 'Asia Pacific'], 
    ['ap-northeast-3', 'Asia Pacific'], 
    ['ap-southeast-1', 'Asia Pacific'], 
    ['ap-southeast-2', 'Asia Pacific'], 
    ['ap-east-1', 'Asia Pacific'], 
    ['ap-south-2', 'Asia Pacific'], 
    ['ap-southeast-3', 'Asia Pacific'], 
    ['ap-southeast-4', 'Asia Pacific'], 
    ['me-south-1', 'Middle East'], 
    ['me-north-1', 'Middle East'], 
    ['il-central-1', 'Middle East'], 
    ['cn-north-1', 'China'], 
    ['cn-northwest-1', 'China'], 
]);